apiVersion: apps/v1
kind: Deployment

metadata:
  name: kafka-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-server
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      containers:
      - name: kafka-server
        image: apache/kafka:4.1.1
        ports:
          - containerPort: 9092
